ALTER TABLE snapshots ALTER COLUMN id DROP DEFAULT;
ALTER TABLE snapshots ALTER COLUMN snapshot_date DROP DEFAULT;

ALTER TABLE categories ALTER COLUMN id DROP DEFAULT;

ALTER TABLE products ALTER COLUMN id DROP DEFAULT;